application:
  name: "WebApp Production"
  version: "2.1.3"
  environment: "production"
  
server:
  port: 8080
  host: "0.0.0.0"
  ssl_enabled: true
  ssl_cert: "/etc/ssl/certs/app.crt"
  ssl_key: "/etc/ssl/private/app.key"

database:
  host: "db-prod-01"
  port: 5432
  name: "app_db"
  username: "app_user"
  connection_pool_size: 20
  timeout: 30

cache:
  type: "redis"
  host: "cache-prod-01"
  port: 6379
  ttl: 3600

services:
  payment_service:
    url: "https://payments.company.com/api/v1"
    timeout: 15
    retry_attempts: 3
    
  notification_service:
    url: "https://notifications.company.com/api/v1"
    timeout: 10

security:
  jwt_secret: "${JWT_SECRET}"
  session_timeout: 1800
  max_login_attempts: 5
  
monitoring:
  metrics_enabled: true
  health_check_interval: 30
  log_level: "INFO"
